image:
  file: .gitpod/Dockerfile
  
  # List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: quarto
    # init: echo 'init script' # runs during prebuild
    command: quarto preview

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - Ikuyadeu.r@1.2.1:z5vr1v1bfS++U/aHLSXQ6Q==
    - quarto.quarto
 
# init/before start steps?   
#      quarto check
#      quarto install tinytex
