---
title: Introduction to the Command Line
author: Thiseas C. Lamnidis, Aida Andrades Valtueña
---

<!-- TODO --> 

::: {.callout-tip}
For this chapter's exercises, if not already performed, you will need to create the [conda environment](before-you-start.qmd#creating-a-conda-environment) from the `yml` file in the following [link](https://github.com/SPAAM-community/intro-to-ancient-metagenomics-book/raw/main/assets/envs/bare-bones-bash.yml) (right click and save as to download), and once created, activate the environment with:

```bash
conda activate bare-bones-bash
```
:::


## Lecture

This is the Brief version of a more Broad two-part session that we gave in 2022, which can be found [here](https://spaam-community.github.io/wss-summer-school/#/2022/day-1?id=practical-1b-bare-bones-bash-1).
The teaching material for the Boundless Bare Bones Bash (Basic + Boosted) can be found in the [Bare Bones Bash website](https://barebonesbash.github.io/#/)

### tl;dr

Below is a quick reference guide to the commands discussed in this tutorial.
To understand actually what each command does, carry on reading below!
For a complete run of all these commands AND MORE(!!),
consider following the full Bare Bones Bash walkthroughs [here](https://barebonesbash.github.io/#/).


| command           | description                                                               | example                                                                                       | common flags or arguments                                                                     |
|-------------------|---------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
| pwd               | print working directory                                                   | pwd                                                                                           |                                                                                               |
| ls                | list contents of directory                                                | ls                                                                                            | -l (long info)                                                                                |
| mkdir             | make directory                                                            | mkdir pen                                                                                     |                                                                                               |
| cd                | change directory                                                          | cd ~/pen                                                                                      | ~ (home dir), - (previous dir)                                                                |
| ssh               | log into a remote server                                                  | ssh <pen>@<apple>.com                                                                         | -Y (allows graphical windows)                                                                 |
| mv                | move something to a new location (& rename if needed)                     | mv pen pineapple                                                                              |                                                                                               |
| rmdir             | remove a directory                                                        | rmdir pineapple                                                                               |                                                                                               |
| wget              | download something from an URL                                            | wget [www.pineapple.com/pen.txt](https://media.giphy.com/media/10fVn57KfQ8Wkw/giphy.gif)      | -i (use input file)                                                                           |
| cat               | print contents of a file to screen                                        | cat pen.txt                                                                                   |                                                                                               |
| gzip              | a tool for dealing with gzip files                                        | gzip pen.txt                                                                                  | -l (show info)                                                                                |
| zcat              | print contents of a gzipped file to screen                                | zcat pen.txt.gz                                                                               |                                                                                               |
| whatis            | get a short description of a program                                      | whatis zcat                                                                                   |                                                                                               |
| man               | print the man(ual) page of a command                                      | man zcat                                                                                      |                                                                                               |
| head              | print first X number of lines of a file to screen                         | head -n 20 pineapple.txt                                                                      | -n (number of lines to show)                                                                  |
| &#124;            | pipe, a way to pass output of one command to another                      | cat pineapple.txt &#124; head                                                                 |                                                                                               |
| tail              | print last X number of lines of a file to screen                          | tail -n 20 pineapple.txt                                                                      | -n (number of lines to show)                                                                  |
| less              | print file to screen, but allow scrolling                                 | less pineapple.txt                                                                            |                                                                                               |
| wc                | tool to count words, lines or bytes of a files                            | wc -l pineapple.txt                                                                           | -l (number of lines not words)                                                                |
| grep              | print to screen lines in a file matching a pattern                        | grep pineapple.txt &#124; grep pen                                                            |                                                                                               |
| ln                | make a (sym)link between a file and a new location                        | ln -s pineapple.txt pineapple_pen.txt                                                         | -s (make _symbolic_ link)                                                                     |
| nano              | user-friendly terminal-based text editor                                  | nano pineapple_pen.txt                                                                        |                                                                                               |
| rm                | more general 'remove' command, including files                            | rm pineapple_pen.txt                                                                          | -r (to remove directories)                                                                    |
| \$VAR              | Dollar sign + text indicates the name of a variable                       | \$PPAP                                                                                       |                                                                                               |
| echo              | prints string to screen                                                   | echo "\$PPAP"                                                                                 |                                                                                               |
| for               | begins 'for' loop, requires 'in', 'do' and 'done'                         | for p in apple pineapple; do <br> echo "\$p\$PPAP"; done <br> <i>applePen pineapplePen</i>    |                                                                                               |
| find              | search for files or directories                                           | find -name 'pen'                                                                              | -type f (search only for files)<br> -name '*JPG' (search for file names matching the pattern) |
| "\$var"            | use double quotes to use contents of variable                             | pen=apple && echo "\$pen"                                                                    |                                                                                               |
|<<br>><br>2>       | redirects the standard input/output/error stream respectively into a file | cat <file.txt >file_copy.txt 2>cat_file.err                                                   |                                                                                               |

### Introduction

The aim of this tutorial is to make you familiar with using bash everyday... 
for the rest of your life! More specifically, we want 
to do this in the context of bioinformatics. We will start with how to navigate 
around a filesystem in the terminal, download sequencing files, and then to
manipulate these. Within these sections we will also show you simple tips and
tricks to make your life generally easier.

This tutorial is designed so you follow along on any machine with a UNIX
terminal (no warranty provided).

### The 5 commandments of Bare Bones Bash

The Bare Bones Bash philosophy of learning to code follows five simple commandments:

|                                                  |                                                                |
|--------------------------------------------------|----------------------------------------------------------------|
| **1)** Be lazy!                                  | Desire for shortcuts motivates you to explore more!            |
| **2)** ~~Google~~ The Hive-Mind knows everything!| 99% of the time, someone else has already had the same issue.  |
| **3)** Document everything you do!               | Make future you happy!                                         |
| **4)** There will ALWAYS be a typo!              | Don't get disheartened, even best programmers make mistakes!   |
| **5)** Don't be afraid of you freedom!           | Explore! Try out things!                                       |

::: {.callout-tip}
## Pro tip
Remember: Noone writes code that works first time, or without looking at StackOverflow sooner or later.
:::

### What is a terminal?

A terminal is simply a fancy window that allows you to access the command-line interface
of a computer or server.

The command-line itself is how you can work on the computer with just text.

`bash` (**b**ourne **a**gain **sh**ell) is one of the most popular languages used in the
terminal.

### Understanding the command prompt

<!-- TODO Add command prompt image here -->

When you open your terminal, it will look something like the image above.
Explain the `$` and the `>`

### Absolute vs Relavtive paths

### Basic commands

### Datastreams, piping, and redirects

### Helptext

### Variables

### Quotes matter!

### find

### For loops

### How to Google like a pro

### (optional) Cleanup

### Summary

<!-- TODO --> 
<!-- Port over condensed walkthrough from BBB website -->