---
title: Deprecated Chapters
---

The following chapters are based on chapters that were taught in earlier edition of the summer schools but are no longer maintained and are kept here for historical purposes, as they may contain useful information.
They may be outdated and may not reflect the current state of the field, and may not reach the same standards as currently maintained chapters.

## [Functional Profiling](functional-profiling.qmd)

The value of microbial taxonomy lies in the implied biochemical properties of a given taxon. Historically taxonomy was determined by growth characteristics and cell properties, and more recently through genomic and genetic similarity. 

The genomic content of microbial taxa, specifically the presence or absence of genes, determine how those taxa interact with their environment, including all the biochemical processes they participate in, both internally and externally. Strains within any microbial species may have different genetic content and therefore may behave strikingly differently in the same environment, which cannot be determined through taxonomic profiling. Functionally profiling a microbial community, or determining all of the genes present independent of the species they are derived from, reveals the biochemical reactions and metabolic products the community may perform and produce, respectively.

This approach may provide insights to community activity and environmental interactions that are hidden when using taxonomic approaches alone. In this chapter we will perform functional profiling of metagenomic communities to assess their genetic content and inferred metabolic pathways.