name: intro-to-ancient-metagenomics-book
dependencies:
  - conda-forge::python
  - conda-forge::pip
  - conda-forge::pipx
  - conda-forge::quarto
  - conda-forge::jupyter
  - conda-forge::pandas
  - conda-forge::matplotlib
  - conda-forge::r-base
  - conda-forge::r-pander