# Introducción {.unnumbered}

La metagenómica antigua aplica métodos metagenómicos de vanguardia al contenido de ADN degradado de especímenes arqueológicos y paleontológicos. Este campo en rápido crecimiento está descubriendo actualmente una gran cantidad de información novedosa tanto para la historia humana como para la natural, desde la identificación de las causas de pandemias devastadoras como la peste negra, hasta la revelación de cómo cambiaron los ecosistemas del pasado en respuesta a los cambios climáticos y antropogénicos a largo plazo, pasando por la reconstrucción de los microbiomas de parientes humanos extintos. Sin embargo, a medida que crece este campo, las técnicas, métodos y flujos de trabajo utilizados para analizar dichos datos cambian y mejoran rápidamente.

En este libro recorreremos los principales pasos de los flujos de trabajo bioinformáticos de la metagenómica antigua, familiarizando a los estudiantes con la línea de comandos, demostrando cómo procesar los datos de secuenciación de próxima generación (NGS), y mostrando cómo realizar el ensamblaje metagenómico de novo. Centrado en la metagenómica antigua asociada al huésped, el libro consiste en una combinación de teoría y ejercicios prácticos, que permite a los lectores familiarizarse con los tipos de preguntas y datos con los que trabajan los investigadores.

Al final del libro de texto, los lectores comprenderán cómo llevar a cabo eficazmente los principales componentes bioinformáticos de un proyecto de metagenómica antigua de forma abierta y transparente.

::: {.callout-note}
Si exportas las versiones PDF o ePub de este libro, algunas secciones pueden quedar excluidas (como los vídeos y las presentaciones de diapositivas incrustadas). En caso de duda, consulta siempre este sitio web.
:::

::: {.callout-warning}
La versión PDF/ePub del libro está todavía en construcción, y es probable que esté mal formateada y que le falte gran parte del contenido. No se recomienda su uso.
:::

*Todo el material se desarrolló originalmente para el [SPAAM](https://spaam-community-github.io) Escuela de Verano: Introducción a la Metagenómica Antigua*

<!-- TODO -->

<!-- Instrucciones sobre cómo navegar por el libro y cómo configurar el entorno computacional - ¿tal vez una página aparte 'antes de empezar'? -->


