---
title: Introduction to NGS Sequencing
author: James A. Fellows Yates
number-depth: 2
---

## Introduction

<!-- TODO -->
<!-- replace all 'I' with 'we' across whole book -->

In this section, I will introduce how we are able to convert DNA
molecules to human readable sequences of A, C, T, and Gs, which we can
subsequently can computationally analyse.

The field of Ancient DNA was revolutionised by the
development of 'Next Generation Sequencing' (NGS), which relies on sequencing of millions
of _short_ fragments of DNA in parallel. The global leading DNA sequencing company is Illumina, and the technology used by Illumina is also most popular by palaeogeneticists. Therefore I will describe
how the various technologies behind Illumina next-generation sequencing machines.

I will also describe some important differences in the way different models
of Illumina sequences work, and how this can influence ancient DNA research. Finally I will
introduce the structure of 'FASTQ' files, the most popular file format for representing the
DNA sequence output of NGS sequencing machines.

## Lecture

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQA8VEi99wl-vMrZDAItfQ7GlXEjyVJEm-Np6j-GBfzGWDz709lOh-IFh2LKzV3WJGUAQ9HvhxHfich/embed?start=false&loop=true&delayms=10000" frameborder="0" width="100%" height="400px" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

PDF version of the slide lectures can be downloaded from [here](https://raw.githubusercontent.com/SPAAM-community/wss-summer-school/main/docs/assets/slides/2022/1a-intro-to-ngs/SPAAM%20Summer%20School%202022%20-%201A%20-%20Introduction%20to%20NGS%20Data.pdf).

<iframe  width="100%" height="400px" src="https://www.youtube.com/embed/ZHlwjD08FBo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<!-- TODO -->
<!-- For all lectures give text pointing to youtube video URL like with PDF -->

## Readings

### Reviews

[@Schuster2008-qx]

[@Shendure2008-fh]

[@Slatko2018-hg]

[@Van_Dijk2014-ep]

### Sequencing Library Construction

[@Kircher2012-fg]

[@Meyer2010-qc]

### Errors and Considerations

[@Ma2019-lg]

[@Sinha2017-zo]

[@Van_der_Valk2019-to]

## Questions to think about

- Why is Illumina sequencing technologies useful for aDNA?
- What problems can the 2-colour chemistry technology of NextSeq and NovaSeqs cause in downstream analysis?
- Why is 'Index-Hopping' a problem?
- What is good software to evaluate the quality of your sequencing runs?
