on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install jupyter
        run: python3 -m pip install jupyter

      - name: Install other required stuff for R
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev librsvg2-bin

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.0"

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::reticulate
            any::rmarkdown
            any::pander
            any::tidyverse
            any::gt
            #any::ggpubr -> has loads of dependency issues, any image should be generated and manually embedded

      - name: Install rsvg-convert
        run: |
          sudo apt-get install -y libimage-librsvg-perl 
          sudo apt-get install -y librsvg2-bin
          rsvg-convert --help

      - name: Install tex
        run: |
          quarto install tinytex

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
